In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

### read

In [2]:
df = pd.read_csv('credit_card.csv')

In [3]:
df

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

### describe

In [4]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [5]:
df.Class.value_counts()

0    284315
1       492
Name: Class, dtype: int64

unbalance dataset, very little information about fraud operations

### split dataset into fraud and normal

In [7]:
normal = df[df.Class == 0]
fraud = df[df.Class == 1]

In [8]:
normal.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [9]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [10]:
df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

### create a sample of normal operations whose length is equal to the length of fraudulent ones

In [11]:
normal_sample = normal.sample(n=len(fraud))

In [12]:
normal_sample

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
90161,62888.0,1.205443,0.289451,0.741620,0.746450,-0.682445,-1.276868,0.136546,-0.284828,-0.106272,...,-0.208169,-0.589665,0.185183,0.933687,0.168355,0.058053,-0.025197,0.027646,11.04,0
124407,77276.0,1.183489,-0.497991,0.753770,-0.962490,-0.856444,0.144266,-0.799290,0.306113,1.667375,...,0.038796,0.333697,-0.052298,-0.299936,0.421663,-0.652053,0.102132,0.017144,1.00,0
274351,165968.0,-0.060557,0.410942,-1.596447,-1.208032,2.506778,3.938650,1.612437,0.374893,-0.255333,...,-0.009669,0.190724,0.062795,0.713937,-0.606090,-0.396005,0.015863,-0.060236,200.06,0
78261,57449.0,1.221511,-1.001374,0.576190,-0.867150,-1.134209,0.093661,-1.024020,0.107171,-0.622582,...,0.432536,0.978686,-0.294968,-0.447211,0.477762,-0.024826,0.016762,0.022580,99.00,0
17874,28997.0,1.120862,0.222902,0.863437,1.456556,-0.414144,-0.208437,-0.056682,-0.003563,0.272104,...,-0.210281,-0.360597,0.102039,0.413654,0.402991,-0.523041,0.060943,0.030384,9.00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82810,59561.0,-2.251724,0.782551,2.260907,1.008504,-0.449630,0.535623,0.700329,-0.293023,1.726055,...,-0.302900,0.666534,-0.484512,0.068577,0.409954,-0.128503,-0.080197,-0.421648,86.70,0
261832,160200.0,2.059715,0.091352,-1.294689,0.329281,0.155307,-1.128356,0.291422,-0.402955,0.374778,...,0.277116,0.985548,0.066097,1.215853,0.279820,-0.171458,-0.016127,-0.045300,1.53,0
13887,24650.0,1.084908,0.225374,0.476370,1.396601,-0.284690,-0.637204,0.069304,-0.166026,1.350272,...,-0.052601,0.026741,-0.052011,0.333432,0.504356,-0.360270,-0.010400,0.020856,53.96,0
60535,49370.0,-0.521355,0.756392,1.277952,1.142962,0.300483,0.522915,0.427733,0.352740,-0.330178,...,-0.002044,0.205594,-0.127005,-0.323212,-0.110544,-0.216828,0.406850,0.191029,28.82,0
242442,151491.0,-3.074812,2.302903,-1.640492,-2.553046,-0.983420,-1.247931,-0.719738,2.109286,-0.234322,...,-0.085911,-0.916808,0.143291,-0.511506,0.062194,0.381818,-0.454263,-0.087348,1.00,0

In [13]:
new_df = pd.concat([normal_sample,fraud])
new_df = new_df.reset_index(drop=True)

In [14]:
new_df

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,62888.0,1.205443,0.289451,0.741620,0.746450,-0.682445,-1.276868,0.136546,-0.284828,-0.106272,...,-0.208169,-0.589665,0.185183,0.933687,0.168355,0.058053,-0.025197,0.027646,11.04,0
1,77276.0,1.183489,-0.497991,0.753770,-0.962490,-0.856444,0.144266,-0.799290,0.306113,1.667375,...,0.038796,0.333697,-0.052298,-0.299936,0.421663,-0.652053,0.102132,0.017144,1.00,0
2,165968.0,-0.060557,0.410942,-1.596447,-1.208032,2.506778,3.938650,1.612437,0.374893,-0.255333,...,-0.009669,0.190724,0.062795,0.713937,-0.606090,-0.396005,0.015863,-0.060236,200.06,0
3,57449.0,1.221511,-1.001374,0.576190,-0.867150,-1.134209,0.093661,-1.024020,0.107171,-0.622582,...,0.432536,0.978686,-0.294968,-0.447211,0.477762,-0.024826,0.016762,0.022580,99.00,0
4,28997.0,1.120862,0.222902,0.863437,1.456556,-0.414144,-0.208437,-0.056682,-0.003563,0.272104,...,-0.210281,-0.360597,0.102039,0.413654,0.402991,-0.523041,0.060943,0.030384,9.00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
979,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
980,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
981,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
982,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
983,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

### Splitting into features and targets

In [15]:
X = new_df.drop(columns='Class', axis=1)
Y = new_df['Class']

In [16]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [17]:
print(X.shape, X_train.shape, X_test.shape)

(984, 30) (787, 30) (197, 30)

### 1st Model: Logistic Regression

In [18]:
model = LogisticRegression()

In [19]:
# training the Logistic Regression Model with Training Data
model.fit(X_train, Y_train)

C:\ProgramData\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

accuracy on training data:

In [20]:
prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(prediction, Y_train)

In [21]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.940279542566709

accuracy on test data:

In [22]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [23]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.9238578680203046

----------

### 2nd Model: Random Forest

In [24]:
from sklearn.preprocessing import StandardScaler

In [25]:
sc = StandardScaler()
df['Amount'] = sc.fit_transform(df[['Amount']])

In [26]:
X2 = df.drop(columns='Class', axis=1)
Y2 = df['Class']

oversampling for imbalance dataset:

In [27]:
from imblearn.over_sampling import SMOTE

In [28]:
sm = SMOTE()

In [29]:
x_res,y_res = sm.fit_resample(X2,Y2)

In [30]:
y_res.value_counts()

0    284315
1    284315
Name: Class, dtype: int64

Splitting into features and targets:

In [31]:
X_train2,X_test2,Y_train2,Y_test2 = train_test_split(x_res,y_res,test_size=0.3,random_state=42)

model:

In [32]:
from sklearn.ensemble import RandomForestClassifier

In [33]:
model2 = RandomForestClassifier()

In [34]:
model2.fit(X_train2,Y_train2)

RandomForestClassifier()

In [36]:
predicted2 = model2.predict(X_test2)

accuracy on test data:

In [37]:
from sklearn.metrics import classification_report,accuracy_score

In [40]:
accuracy_score(Y_test2, predicted2)

0.9999062073170016